version: '3.4'

services:
  api_desafio.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Default=Host=api.db;Port=5432;Database=ApiDesafio;Username=postgres;Password=postgres
    ports:
      - "7070:8080"
      - "7071:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
        - api.db

  api.db:
    container_name: api.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ApiDesafio
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - ./postgres_api.db:/var/lib/postgresql/data/ 

  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080